### ISSUE TITLE
The online demo is broken

### ISSUE THREAD

**Issue by IonicaBizau** [mojotech/social-builder#44]
![image](https://cloud.githubusercontent.com/assets/2864371/6575690/c9e065c2-c739-11e4-8716-5daa25e1de76.png)

**Comment by samccone** [comment]
@IonicaBizau thanks for the bug good catch! we will have this fixed asap

:clap:

**Comment by IonicaBizau** [comment]
Thanks! I love this builder! :+1:

**Comment by samccone** [comment]
hey @IonicaBizau ok first step done, we need to go in and change all the hard coded http to be protocol agnostic using the `//` syntax.

**Comment by IonicaBizau** [comment]
I can do that. Will submit a PR today.

**Comment by samccone** [comment]
oh awesome! thanks so much, if you are too busy let me know and I can go in and finish it up

**Comment by sethkrasnianski** [comment]
:+1:
