### ISSUE TITLE
Twitter and Pinterest images are broken

### ISSUE THREAD

**Issue by IonicaBizau** [mojotech/social-builder#47]
Not sure what happened, but it looks like the image is not there anymore.

![image](https://cloud.githubusercontent.com/assets/2864371/22782472/f379ac9e-eecf-11e6-89df-38974c2deb39.png)

**Comment by IonicaBizau** [comment]
![image](https://cloud.githubusercontent.com/assets/2864371/22782504/115f24b4-eed0-11e6-9435-935608839aab.png)

**Comment by samccone** [comment]
heh, @wkf @mforsyth 

I no longer work @ mojotech ... guessing someone killed the s3 bucket

**Comment by wkf** [comment]
Thanks for the report! @samccone mind opening a PR?

**Comment by IonicaBizau** [comment]
Putting these images back on the same urls would be great. I use these urls in quite a few apps...

**Comment by mordecai174** [comment]
alrighty, all should be well now. sorry about that, not sure what happened...

**Comment by mordecai174** [comment]
@IonicaBizau 👍

**Comment by IonicaBizau** [comment]
Works! Thanks! 👍
